name: .NET

on:
  workflow_dispatch:

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 2.1.x
    - name: Restore dependencies
      run: dotnet restore .\EleviaUI\
    - name: Build
      run: dotnet build .\EleviaUI\ --no-restore
    - name: Test
      run: dotnet test .\EleviaUI\ --logger:nunit --no-build --verbosity normal
    - name: Submit results to Xray1
      uses: mikepenz/xray-action@v2.4.0
      with:
        username: "A1E23A8D4286423BAD3F756D2DBC7C71"
        password: "16075782d137236f5e72b7ffce458f455ca6758e8d04bc93f5a539a1a56e42b0"
        testPaths: "**/TestResults.xml"
        projectKey: "TXE"
        testExecKey: "TXE-01"
        testFormat: "nunit"
    - name: Submit results to Xray2
      uses: mikepenz/xray-action@v2.4.0
      with:
        username: "A1E23A8D4286423BAD3F756D2DBC7C71"
        password: "16075782d137236f5e72b7ffce458f455ca6758e8d04bc93f5a539a1a56e42b0"
        testPaths: "**/TestResults/TestResults.xml"
        projectKey: "TXE"
        testExecKey: "TXE-01"
        testFormat: "nunit"
    - name: Submit results to Xray3
      uses: mikepenz/xray-action@v2.4.0
      with:
        username: "A1E23A8D4286423BAD3F756D2DBC7C71"
        password: "16075782d137236f5e72b7ffce458f455ca6758e8d04bc93f5a539a1a56e42b0"
        testPaths: "TestResults.xml"
        projectKey: "TXE"
        testExecKey: "TXE-01"
        testFormat: "nunit"
    - name: Submit results to Xray4
      uses: mikepenz/xray-action@v2.4.0
      with:
        username: "A1E23A8D4286423BAD3F756D2DBC7C71"
        password: "16075782d137236f5e72b7ffce458f455ca6758e8d04bc93f5a539a1a56e42b0"
        testPaths: "**/EleviaUI/TestResults.xml"
        projectKey: "TXE"
        testExecKey: "TXE-01"
        testFormat: "nunit"
    - name: Submit results to Xray4
      uses: mikepenz/xray-action@v2.4.0
      with:
        username: "A1E23A8D4286423BAD3F756D2DBC7C71"
        password: "16075782d137236f5e72b7ffce458f455ca6758e8d04bc93f5a539a1a56e42b0"
        testPaths: "EleviaUI/TestResults.xml"
        projectKey: "TXE"
        testExecKey: "TXE-01"
        testFormat: "nunit"
