name: main

on:
  workflow_dispatch:

jobs:
  build:

    runs-on: windows-latest

    steps:
    - name: Submit results to Xray
      uses: mikepenz/xray-action@v0.9.4
      with:
        testPaths: "**/TestResults/TestResults.xml"
        projectKey: "PXS"
        testExecKey: "PXS-01"
